# Generated by Django 4.0.5 on 2022-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='auther github'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='auther instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='auther telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='auther twitter'),
        ),
    ]
