# Generated by Django 4.0.5 on 2022-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_github_user_instagram_user_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team',
            field=models.BooleanField(default=False, verbose_name='Is this user a team member?'),
        ),
    ]
