# Generated by Django 4.0.5 on 2022-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'email already exists'}, max_length=150, null=True, unique=True, verbose_name='last name'),
        ),
    ]
