# Generated by Django 4.0.5 on 2022-07-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribtionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name user')),
                ('email', models.EmailField(max_length=250, verbose_name='email user')),
                ('title', models.CharField(max_length=100, verbose_name='title ticket')),
                ('message', models.TextField(max_length=500, verbose_name='messge ticket')),
                ('accepted', models.BooleanField(default=False)),
                ('admin_response', models.CharField(blank=True, max_length=500, verbose_name='admin answer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender user')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='category name/title')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='category description')),
                ('image', models.ImageField(upload_to='media', verbose_name='category image')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='blog title')),
                ('description', models.TextField(verbose_name='blog description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='blog date')),
                ('image', models.ImageField(upload_to='media', verbose_name='blog image')),
                ('is_image_header', models.BooleanField(default=True, verbose_name='is header image?')),
                ('slug', models.SlugField(verbose_name='blog slug')),
                ('status', models.CharField(choices=[('public', 'public'), ('draft', 'draft')], default='draft', max_length=50, verbose_name='blog status')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='blog auther')),
            ],
        ),
    ]
