# Generated by Django 4.0.5 on 2022-07-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categorymodels', verbose_name='blog category'),
        ),
        migrations.AddField(
            model_name='categorymodels',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chlidern', to='blog.categorymodels', verbose_name='category parend'),
        ),
    ]
