# Generated by Django 4.0.5 on 2022-07-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categorymodels_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodels',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='blog.categorymodels', verbose_name='category parend'),
        ),
    ]
