# Generated by Django 4.0.5 on 2022-07-17 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auther_articles', to=settings.AUTH_USER_MODEL, verbose_name='blog auther'),
        ),
    ]
